# Site settings
title: "Portfolio d'Antoine Allard"
email: antoine.allard@epitech.fr
description: >- 
  Étudiant à Epitech - Portfolio professionnel présentant mes projets de développement
  et mon parcours dans le numérique.
baseurl: "/Portfolio" 
url: "https://antoineall.github.io/Portfolio/" #https://AntoineAll.github.io 
github_username: AntoineAll

collections:
  projects:
    output: true
    permalink: /realisation/:path/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
#exclude:
#  - Gemfile
 # - Gemfile.lock
  #- node_modules/
  #- vendor/